# Generated by Django 3.2.5 on 2022-05-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_group', to='benedict_option.group'),
        ),
    ]
