# Generated by Django 3.2.5 on 2022-07-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liturgy',
            options={'verbose_name_plural': 'liturgies'},
        ),
    ]
