# Generated by Django 3.2.5 on 2022-09-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_invite',
            name='user',
        ),
    ]
