# Generated by Django 3.2.5 on 2022-05-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0002_textmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TextModel',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_prayers',
            field=models.ManyToManyField(related_name='favorite_prayers', to='benedict_option.Prayer'),
        ),
        migrations.AddField(
            model_name='user',
            name='uploaded_prayers',
            field=models.ManyToManyField(related_name='uploaded_prayers', to='benedict_option.Prayer'),
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_prayers',
            field=models.ManyToManyField(related_name='viewed_prayers', to='benedict_option.Prayer'),
        ),
    ]
