# Generated by Django 3.2.5 on 2022-09-07 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0002_auto_20220906_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer_request',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='benedict_option.comment'),
        ),
    ]
