# Generated by Django 3.2.5 on 2022-09-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0003_alter_prayer_request_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer_request',
            name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='prayer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='benedict_option.prayer_request'),
        ),
    ]
