# Generated by Django 3.2.5 on 2022-09-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0003_alter_group_invite_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_invite',
            name='receiver',
        ),
        migrations.AddField(
            model_name='user',
            name='group_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to='benedict_option.group_invite'),
        ),
    ]
