# Generated by Django 3.2.5 on 2022-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0003_auto_20220504_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
