# Generated by Django 3.2.5 on 2022-07-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0004_auto_20220729_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_group',
        ),
        migrations.AddField(
            model_name='user',
            name='current_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_group', to='benedict_option.Group'),
        ),
    ]
