# Generated by Django 3.2.5 on 2022-09-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0005_alter_liturgy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liturgy',
            options={'verbose_name_plural': 'liturgies'},
        ),
    ]
