# Generated by Django 3.2.5 on 2022-09-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0005_auto_20220923_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_invitation',
            new_name='group_invitations',
        ),
        migrations.AddField(
            model_name='group_invite',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
