# Generated by Django 3.2.5 on 2022-07-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0005_auto_20220729_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_groups',
            field=models.ManyToManyField(blank=True, related_name='current_group', to='benedict_option.Group'),
        ),
    ]
