# Generated by Django 3.2.5 on 2022-05-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0006_auto_20220510_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_group', to='benedict_option.group'),
            preserve_default=False,
        ),
    ]
