# Generated by Django 3.2.5 on 2022-09-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benedict_option', '0006_auto_20220923_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_invitations',
        ),
    ]
